export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SEAT_TAKEN: 'SEAT_TAKEN',
  BOOKING_EXPIRED: 'BOOKING_EXPIRED',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL: 'INTERNAL',
};

export const MAX_SEATS_PER_BOOKING = 6;
export const SEAT_HOLD_SECONDS = 15 * 60; // 900 seconds

export const AUTH_PROVIDERS = {
  LOCAL: 'LOCAL',
  GOOGLE: 'GOOGLE',
};

export const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  LOCKED: 'LOCKED',
  DELETED: 'DELETED',
};

export const MOVIE_STATUS = {
  COMING_SOON: 'COMING_SOON',
  NOW_SHOWING: 'NOW_SHOWING',
  ENDED: 'ENDED',
};

export const AGE_RATINGS = {
  P: 'P',
  K: 'K',
  T13: 'T13',
  T16: 'T16',
  T18: 'T18',
  C: 'C',
};

export const SCREEN_FORMATS = {
  TWO_D: 'TWO_D',
  THREE_D: 'THREE_D',
  IMAX: 'IMAX',
  FOUR_DX: 'FOUR_DX',
  SCREENX: 'SCREENX',
  DOLBY: 'DOLBY',
  LED: 'LED',
};

export const ROOM_TIERS = {
  STANDARD: 'STANDARD',
  VIP: 'VIP',
  KIDS: 'KIDS',
  PREMIUM: 'PREMIUM',
};

export const SHOWTIME_KINDS = {
  REGULAR: 'REGULAR',
  ENCORE: 'ENCORE',
  LIVE: 'LIVE',
};

export const CAPTION_MODES = {
  SUBTITLED: 'SUBTITLED',
  DUBBED: 'DUBBED',
};

export const SEAT_STATES = {
  AVAILABLE: 'AVAILABLE',
  HELD: 'HELD',
  SOLD: 'SOLD',
  BLOCKED: 'BLOCKED',
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_PROVIDERS = {
  VNPAY: 'VNPAY',
  ZALOPAY: 'ZALOPAY',
  MOMO: 'MOMO',
};

export const PAYMENT_STATUS = {
  INITIATED: 'INITIATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

export const TICKET_STATUS = {
  VALID: 'VALID',
  USED: 'USED',
  VOID: 'VOID',
};

export const VOUCHER_TYPES = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
};

export const REDEMPTION_STATUS = {
  RESERVED: 'RESERVED',
  REDEEMED: 'REDEEMED',
  RELEASED: 'RELEASED',
};

export const CONCESSION_CATEGORIES = {
  COMBO: 'COMBO',
  POPCORN: 'POPCORN',
  DRINK: 'DRINK',
  SNACK: 'SNACK',
};

export const PRICE_SOURCES = {
  CRAWLED: 'CRAWLED',
  DEFAULT: 'DEFAULT',
  MANUAL: 'MANUAL',
};

export const DAY_TYPES = {
  WEEKDAY: 'WEEKDAY',
  WEEKEND: 'WEEKEND',
  HOLIDAY: 'HOLIDAY',
};
